---
name: Create weekly action
description: Action that creates a consistent issue on different dates.
branding:
  icon: 'users'  
  color: 'yellow'
inputs:
  date_string:
    description: Date string used to add the date to the title of the issue
    default: this friday
    required: true
  title:
    default: 'Weekly issue for week of <date>'
  labels:
    default: 'weekly-sync'
    required: false
  body:
    default: "Weekly sync issue for the week of ${{outputs.sdfsdf }}"
  pinned: 
    default: true
    description: Whether the issue should be pinned.
  close_previous:
    default: true
    description: Whether to close the previous weekly issue when creating new one
  linked-comments:
    default: true
    description: Whether to link to the previous weekly issue when creating a new one
  assignees: 
    description: Assignees for the issue
    required: false
  token: 
    description: GitHub token
    required: true
    default: ${{ github.token }}
outputs:
  date:
    description: The date of the issue
    value: ${{ steps.date.outputs.date  }}
runs:
  using: composite
  steps:
    - name: get date
      id: date
      run: |
        echo "::set-output name=date::$(date -d ${{inputs.date_string}} +"%m/%d/%Y")"
    - uses: imjohnbo/issue-bot@v3
      with:
        assignees: ${{ input.assignees }}
        labels: ${{ input.labels }}
        title: ${{ inputs.title }} for week of ${{ steps.date.outputs.date }}
        body: ${{ inputs.body }}
        pinned: ${{ inputs.pinned }}
        close-previous: ${{ inputs.close_previous }}
        linked-comments: ${{ inputs.linked=comments }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
